export const TEAMS = [
    "albania",
    "austria",
    "belgium",
    "croatia",
    "czechia",
    "denmark",
    "england",
    "france",
    "georgia",
    "germany",
    "hungary",
    "italy",
    "netherlands",
    "poland",
    "portugal",
    "romania",
    "scotland",
    "serbia",
    "slovakia",
    "slovenia",
    "spain",
    "switzerland",
    "turkey",
    "ukraine"
]

export const COUNTRY_CODES: { [key: string]: string } = {
    "albania": "ALB",
    "austria": "AUT",
    "belgium": "BEL",
    "croatia": "HRV",
    "czechia": "CZE",
    "denmark": "DNK",
    "england": "ENG",
    "france": "FRA",
    "georgia": "GEO",
    "germany": "GER",
    "hungary": "HUN",
    "italy": "ITA",
    "netherlands": "NLD",
    "poland": "POL",
    "portugal": "PRT",
    "romania": "ROU",
    "scotland": "SCO",
    "serbia": "SRB",
    "slovakia": "SVK",
    "slovenia": "SVN",
    "spain": "ESP",
    "switzerland": "CHE",
    "turkey": "TUR",
    "ukraine": "UKR"
};

export const UEFA_RANKINGS: { [key: string]: number } = {
    "albania": 37,
    "austria": 10,
    "belgium": 9,
    "croatia": 8,
    "czechia": 13,
    "denmark": 15,
    "england": 1,
    "france": 5,
    "georgia": 32,
    "germany": 3,
    "hungary": 29,
    "italy": 2,
    "netherlands": 6,
    "poland": 25,
    "portugal": 7,
    "romania": 26,
    "scotland": 11,
    "serbia": 20,
    "slovakia": 22,
    "slovenia": 23,
    "spain": 4,
    "switzerland": 12,
    "turkey": 19,
    "ukraine": 16
};